---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64
clone:
  disable: true
steps:
- name: download
  commands:
  - cd /opt/www/htdocs/os && wget https://github.com/lxsang/antos/raw/1.2.1/release/antos-1.2.1.tar.gz
- name: build
  commands:
  - cd /opt/www/htdocs/os && tar xvzf antos-1.2.1.tar.gz
  - rm /opt/www/htdocs/os/antos-1.2.1.tar.gz
trigger:
  branch:
  - 1.2.1
