# {0}
This is an example project, generated by AntOS Development Kit

## Howto
Use the CodePad command palette to access to the SDK functionalities:

1. Create new project
2. Init the project from the current folder located in side bar
3. Build and run the project
4. Release the project in zip package

## Set up build target

Open the `project.json` file from the current project tree and add/remove
build target entries. Save the file