# {0}
This is an example project, generated by AntOS Development Kit

## Howto

1. Open the project.apj file with AntOSDK (simply double Click on it)
2. Modify the UI in *assets/scheme.html*
3. Modify application code in *coffees/main.coffee*
4. Modify CSS style in *css/main.css*
5. Other files need to be copied: put in to assets

## Set up build target

Click **Menu> Build > Build Option** or simply hit **ALT-Y**

In the build options dialog, add or remove files that need to be
included into the build

Click **Save**

## Build application
* To build: **Menu > Build > Build** or **ALT-C**
* To build and run: **Menu > Build > Build and Run** or **CTRL-R**
* To release: **Menu > Build > Build release** or **ALT-P**